# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d163e9ee68716ba2a94b696d3416aab3f4122d2687a8e30309c045729c788e2092702ca8d7f0209ebf6af20fa705c6276f3383e1e19f08ad3e4a9a5fbdb8eba7

test:
  secret_key_base: 7d5c0fc2af49be8e107bfb29271c14eb70ee356a215e2a7674582e6f3b25c873a3faae55d6682c3748ce3058afcaed80e6e55015fbecc18af4f61352a3870fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
